# Generated by Django 2.0.5 on 2024-03-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('dept_id', models.IntegerField()),
                ('credits', models.IntegerField()),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'courses',
            },
        ),
    ]
